itos_url: "https://apps.itos.uga.edu/CODV2API/api/v1/Locations/all"

itos_ps_url: "https://apps.itos.uga.edu/CODV2API/api/v1/themes/cod-ps/lookup/Get/0/do/"

boundaries:
  dataset_exceptions:
    MMR:
      - "mimu-geonode-myanmar-national-boundary-mimu"
      - "mimu-geonode-myanmar-district-boundaries-mimu"
      - "mimu-geonode-myanmar-state-and-region-boundaries-mimu"
      - "mimu-geonode-myanmar-state-and-region-boundaries-with-sub-regions-mimu"
