# This workflow will install Python dependencies and run the script

name: run

on:
  workflow_dispatch: # add run button in github
  schedule:
    - cron: "0 22 * * *"

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run script
      env:
        HDX_READ_ONLY: ${{ secrets.HDX_READ_ONLY }}
        HDX_SITE: ${{ secrets.HDX_SITE }}
        PREPREFIX: ${{ secrets.PREPREFIX }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
      run: |
        python run.py
    - name: Commit updated data bundle
      if: always()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: datasets*.csv population*.csv
        commit_message: automatic - csv updated
        push_options: '--force'
        skip_dirty_check: false
